version: '2'
services:
  influxdb:
    extends:
      file: docker-compose.yml
      service: influxdb
    environment:
      CONSUL: ""
  grafana:
    extends:
      file: docker-compose.yml
      service: grafana
    environment:
      CONSUL: ""
    depends_on:
      - influxdb
